# Generated by Django 5.0.6 on 2024-07-12 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Associate Manager', 'Associate Manager'), ('Team Leader', 'Team Leader'), ('Member', 'Member')], default='Member', max_length=100)),
                ('pending', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('details', models.TextField()),
                ('members', models.ManyToManyField(blank=True, to='workspace.member')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('details', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('To Do', 'To Do'), ('Done', 'Done')], default='To Do', max_length=100, null=True)),
                ('priority', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MID', 'Mid'), ('HIGH', 'High')], default='LOW', max_length=100, null=True)),
                ('which_Type', models.CharField(blank=True, choices=[('Feature', 'Feature'), ('Bug Fix', 'Bug Fix'), ('Code Test', 'Code Test'), ('Task', 'Task')], default='Task', max_length=100, null=True)),
                ('task_Value', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.member')),
                ('scrum_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.scrum')),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('commenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.member')),
                ('task_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.task')),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('details', models.TextField(blank=True, null=True)),
                ('start_Date', models.DateField()),
                ('end_Date', models.DateField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('remaining_time', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('To Do', 'To Do'), ('Testing', 'Testing'), ('Done', 'Done')], default='To Do', max_length=100)),
                ('assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.member')),
            ],
        ),
        migrations.AddField(
            model_name='scrum',
            name='timeline_Name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.timeline'),
        ),
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('workSpace_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='timeline',
            name='workspace_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace'),
        ),
        migrations.AddField(
            model_name='member',
            name='workspace_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('workspace_Name', 'user')},
        ),
    ]
