# Generated by Django 5.0.6 on 2024-06-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrum',
            name='members',
        ),
        migrations.AddField(
            model_name='scrum',
            name='members',
            field=models.ManyToManyField(blank=True, to='workspace.member'),
        ),
    ]
